v# Project
version=0.6.0
group=com.teammetallurgy.masonry
java_version=25

# Common
minecraft_version=26.1
mod_name=Masonry
mod_author=Shadowclaimer, Vequinox
mod_id=masonry
license=GNU Lesser General Public License, version 2.1
credits=Shadowclaimer - Artist/Designer, Vequinox - Programmer, Girafi - Programmer
description=Masonry is a mod that adds more decorative block options to the Stonecutter's recipe list, as well as a few craftable blocks.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.3+26.1
fabric_loader_version=0.18.5

# NeoForge
neoforge_version=26.1.0.5-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[26.1.0.0,)
jei_version=19.21.0.247

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
