modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/TeamMetallurgy/Masonry/issues"

[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    version = "${version}" #mandatory
    displayName = "${mod_name}" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/masonry"
    #logoFile="logo.png" #optional
    credits="${credits}" #optional
    authors = "${mod_author}" #optional
    description = '''${description}''' #mandatory (Supports multiline text)

[[dependencies.${mod_id}]] #optional
    modId = "neoforge" #mandatory
    type = "required"
    versionRange = "${neoforge_loader_version_range}" #mandatory
    ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
    side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"